name: psycholog

services:
  blog:
    type: ruby
    build_as_root:
      - apt-get update
      - apt-get install -y nodejs
    build:
      - gem install bundler
      - bundle install
    command: bundle exec jekyll serve --port 8080 --host 0.0.0.0 --incremental

proxy:
  blog:
    - psycholog.lndo.site:8080
